### ISSUE TITLE
缩放有时会跳动一下，中心点都变了，图片移动也会抖动，并且缩放率太大，很容易就缩放到最大了

### ISSUE THREAD

**Issue by tangxianqiang** [xshu1996/MapControl-master#2]
缩放有时会跳动一下，中心点都变了，图片移动也会抖动，并且缩放率太大，很容易就缩放到最大了

**Comment by xshu1996** [comment]
现在新增了速率控制的参数， 缩放偶尔会跳动的原因可能是由于速率过大导致 可以通过线性插值处理看起来更平滑一点

**Comment by tangxianqiang** [comment]
@xshu1996  是的，我后面仔细看了代码，缩放速率会出现暴增的现象，我觉得可以通过阻尼运动函数解决这个问题，就像高德地图一样；至于缩放跳动的问题是缩小到100%零界点的时候防止出现 小于100%的问题而对中心点位置进行了设置；我觉得这两个优化了会很好用。（我的demo是针对一个超出屏幕的一个图片测试的，手机像素是1920*1080,图片宽高均大于这个分辨率）
